# Generated by Django 6.0.2 on 2026-02-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100)),
                ('disease_tag', models.CharField(max_length=100)),
                ('reading_value', models.FloatField()),
            ],
        ),
    ]
